export const USER_MESSAGES = {
	USER_INFORMATION_GENERAL_ERROR: "Error al obtener la información del usuario",
	USER_INFORMATION_SUCCESSFUL: "Información del usuario obtenida con éxito",
	USER_PARTY_VERIFICATION_ERROR: "Error al verificar el estado de la party",
	USER_PARTY_VERIFICATION_SUCCESSFUL: "Estado de la party verificado con éxito",
	USER_PARTY_CREATE_SUCCESSFUL: "Se creó la sala correctamente",
	USER_PARTY_CREATE_ERROR: "Error al crear la party",
	USER_PARTY_DROP_MEMBER_ERROR_PARAM: "Error al eliminar miembro de la party, parámetros incorrectos",
	USER_PARTY_DROP_MEMBER_SUCCESSFUL: "Has salido correctamente de la sala",
	USER_PARTY_DROP_MEMBER_GENERAL_ERROR: "Error al salir de la cola",
	USER_PARTY_DROP_ERROR_PARAM: "Error al eliminar la party, parámetros incorrectos",
	USER_PARTY_DROP_GENERAL_ERROR: "Error al eliminar la party",
	USER_PARTY_DROP_SUCCESSFULL: "Se ha eliminado la party correctamente",
	USER_PARTY_JOIN_MEMBER_ERROR_PARAMS: "Error al unirse a la party, parámetros incorrectos",
	USER_PARTY_JOIN_NOT_FOUND: "No se ha encontrado la party",
	USER_PARTY_JOIN_GENERAL_ERROR: "Error general al unirse a la party",
	USER_PARTY_JOIN_SUCCESSFUL: "Te has unido a la party correctamente",
	USER_GET_CONNECTION_SUCCESSFUL: "Verificación de usuarios en linea",
	USER_GET_CONNECTION_STATUS_ERROR: "Hubo un error al verificar los usuarios en linea",
	USER_REGION_ERROR_PARAM: "Parámetros incompletos",
	USER_REGION_ERROR_GENERAL: "Error general al actualizar la región",
	USER_REGION_SUCCESSFUL: "Región actualizada",
	USER_CURRENT_GAME_GENERAL_ERROR: "Hubo un error general al buscar el juego actual",
	USER_CURRENT_GAME_SUCCESS: "Juego encontrado correctamente",
	USER_ONLINE_LIST_SUCCESS: "Usuarios en linea encontrados",
	USER_ONLINE_LIST_GENERAL_ERROR: "Error general al listar los usuarios",
	USER_CONFIG_SUCCESSFUL:"Se actualizó la configuración del usuario",
	USER_CONFIG_NOT_UPDATED:"No se pudo actualizar la configuración",
	USER_CONFIG_GENERAL_ERROR:"Hubo un error general al actualizar la configuración"
};

export const QUEUE_MESSAGES = {
	QUEUE_JOIN_ROOM_NOT_FOUND: "Parámetros incorrectos",
	QUEUE_JOIN_NOT_REGION_DETECTED: "Por favor selecciona una región",
	QUEUE_JOIN_GENERAL_ERROR: "Error general al unirse a la cola",
	QUEUE_JOIN_ALREADY_JOINED: "Ya estás en la cola",
	QUEUE_JOIN_ALREADY_GAME: "Ya estás en una partida",
	QUEUE_JOIN_WAIT_TIME: "Vuelve a intentarlo en unos segundos",
	QUEUE_JOIN_SUCCESSFUL: "Te has unido a la cola correctamente",
	QUEUE_LIST_ERROR_PARAM: "Parámetros incorrectos al listar la cola",
	QUEUE_LIST_ERROR_GENERAL: "Error general al listar la cola",
	QUEUE_LIST_SUCCESSFUL: "Lista de usuarios",
	QUEUE_DROP_SUCCESSFUL: "Se salio de la cola correctamente",
	QUEUE_DROP_GENERAL_ERROR: "Hubo un error general al salir de la cola",
	QUEUE_PARTY_JOIN_SUCCESSFUL: "Están en la cola.",
	QUEUE_PARTY_JOIN_GENERAL_ERROR: "Ha ocurrido un error general al unirse a la cola en grupo.",
	QUEUE_PARTY_JOIN_NOT_REGION: "El siguiente usuario no ha seleccionado una región",
	QUEUE_PARTY_JOIN_GAME_PLAYING: "El siguiente usuario se encuentra en una partida",
	QUEUE_PARTY_ERROR_FOUND:"Se encontró un error con algún miembro de la party",
	QUEUE_PARTY_DROP_SUCCESSFUL: "El party se salió de la cola",
	QUEUE_PARTY_DROP_GENERAL_ERROR: "Hubo un error al salir de la cola como party",
	QUEUE_GAMES_INVALID_PARAM: "Parámetros incorrectos, falta room",
	QUEUE_GAMES_SUCCESSFULL: "Lista de juegos activos",
	QUEUE_GAMES_GENERAL_ERROR:"Hubo un error general al listar los juegos"
};

export const SOCKET_MESSAGES = {
	SOCKET_DISCONNECT_ERROR: "Hubo un error al desconectarse del socket",
};
